name: ggwsm
description: Bridge from gg to ggwsm (WASM version of gg)
version: 0.0.4
repository: https://github.com/tssuite/ggwsm.git
publish_to: none

environment:
  sdk: '>=3.11.0 <4.0.0'

dependencies:
  web: ^1.1.1
  gg: ^17.3.0
  gg_log: ^1.2.0
dev_dependencies:
  gg_console_colors: ^2.4.0
  helix: ^1.3.0
  lints: ^6.1.0
  test: ^1.31.2
